Always run phplint
D3R/github-workflows pull request #9
Opened 2023-01-14 13:19 UTC by mrjatkin

2023-01-16 12:30 UTC, dmnc requested changes
Added some more excludes

2023-01-16 12:30 UTC, dmnc commented on .github/workflows/d3r-standard-php-ci.yaml
> +            phplint --cache="${PHPLINT_CACHE}" --exclude="vendor"
```suggestion
            phplint --cache="${PHPLINT_CACHE}" --exclude=vendor --exclude=build --exclude=tmp
```

2023-02-15 11:04 UTC, mrjatkin commented on .github/workflows/d3r-standard-php-ci.yaml
> +            phplint --cache="${PHPLINT_CACHE}" --exclude="vendor"
Fixed in c6f200e.

2023-02-15 11:22 UTC, dmnc approved these changes

2023-02-15 11:37 UTC, merged